const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_16_04_11_01_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODgsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMixcbiAgICAgICAgMTMzLFxuICAgICAgICA4MixcbiAgICAgICAgMTgsXG4gICAgICAgIDQzLFxuICAgICAgICA2MCxcbiAgICAgICAgMCxcbiAgICAgICAgMTkwLFxuICAgICAgICAxODAsXG4gICAgICAgIDYwLFxuICAgICAgICA0NCxcbiAgICAgICAgMjMwLFxuICAgICAgICA2OCxcbiAgICAgICAgMTc1LFxuICAgICAgICA5NSxcbiAgICAgICAgNjMsXG4gICAgICAgIDE2MCxcbiAgICAgICAgNzgsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjExLFxuICAgICAgICAyMDMsXG4gICAgICAgIDMwLFxuICAgICAgICAyMDgsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjE3LFxuICAgICAgICA1LFxuICAgICAgICAzOSxcbiAgICAgICAgOTEsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTAzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxMDAsXG4gICAgICAgIDY1LFxuICAgICAgICA4MSxcbiAgICAgICAgOTksXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTA5LFxuICAgICAgICA2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDU1LFxuICAgICAgICA1MCxcbiAgICAgICAgMjU1LFxuICAgICAgICA0LFxuICAgICAgICAyNSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxODksXG4gICAgICAgIDIxMixcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDUwLFxuICAgICAgICA3NCxcbiAgICAgICAgNTksXG4gICAgICAgIDg2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjUwLFxuICAgICAgICA0NSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMTAsXG4gICAgICAgIDg3LFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDg4LFxuICAgICAgICAxMzUsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTkwLFxuICAgICAgICA2NyxcbiAgICAgICAgNSxcbiAgICAgICAgMTEzLFxuICAgICAgICAxOTYsXG4gICAgICAgIDkyLFxuICAgICAgICAyOCxcbiAgICAgICAgMjE5LFxuICAgICAgICA4NixcbiAgICAgICAgMTk4LFxuICAgICAgICAxMTEsXG4gICAgICAgIDYwLFxuICAgICAgICAxNDQsXG4gICAgICAgIDcwLFxuICAgICAgICAyMzYsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxOTQsXG4gICAgICAgIDE4MixcbiAgICAgICAgMzUsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTg2LFxuICAgICAgICAxOTksXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNDAsXG4gICAgICAgIDUzLFxuICAgICAgICAxMCxcbiAgICAgICAgODFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ2LFxuICAgICAgICA5NSxcbiAgICAgICAgMTE0LFxuICAgICAgICA5NSxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMTQsXG4gICAgICAgIDQyLFxuICAgICAgICAxMTUsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMyxcbiAgICAgICAgMTc1LFxuICAgICAgICA3MixcbiAgICAgICAgMTkxLFxuICAgICAgICA4MSxcbiAgICAgICAgNzYsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjI4LFxuICAgICAgICA1NixcbiAgICAgICAgMTAwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE4MyxcbiAgICAgICAgODksXG4gICAgICAgIDE5NixcbiAgICAgICAgMjEsXG4gICAgICAgIDIwMSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNzEsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTE5LFxuICAgICAgICAyNDMsXG4gICAgICAgIDY3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA2NCxcbiAgICAgICAgMTQsXG4gICAgICAgIDI1LFxuICAgICAgICAxNzEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTU2LFxuICAgICAgICAxNSxcbiAgICAgICAgMTMsXG4gICAgICAgIDE0LFxuICAgICAgICAzMSxcbiAgICAgICAgOTUsXG4gICAgICAgIDExOSxcbiAgICAgICAgODMsXG4gICAgICAgIDcwLFxuICAgICAgICAxNjUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTE5LFxuICAgICAgICAxNTYsXG4gICAgICAgIDQ2LFxuICAgICAgICA3OCxcbiAgICAgICAgNTIsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTI0LFxuICAgICAgICAxNzgsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTg1LFxuICAgICAgICA0NSxcbiAgICAgICAgMjEyLFxuICAgICAgICAxMTgsXG4gICAgICAgIDE1LFxuICAgICAgICAxMjYsXG4gICAgICAgIDg4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0LFxuICAgICAgICA3OSxcbiAgICAgICAgODAsXG4gICAgICAgIDc2LFxuICAgICAgICA1MSxcbiAgICAgICAgMjQyLFxuICAgICAgICAyMzAsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTIsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMzIsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTA0LFxuICAgICAgICAzNSxcbiAgICAgICAgMjExLFxuICAgICAgICA5NixcbiAgICAgICAgMjUzLFxuICAgICAgICAxODYsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTkzLFxuICAgICAgICAyMTgsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTgxLFxuICAgICAgICA0MyxcbiAgICAgICAgNzUsXG4gICAgICAgIDk2LFxuICAgICAgICAyMDAsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMzQsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjE1LFxuICAgICAgICA4MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA3MlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDY1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAzLFxuICAgICAgICAxOCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDEyLFxuICAgICAgICAxNDMsXG4gICAgICAgIDcwLFxuICAgICAgICAxMzcsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMzQsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNzAsXG4gICAgICAgIDExNixcbiAgICAgICAgNjIsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNTgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgODEsXG4gICAgICAgIDg5LFxuICAgICAgICAxOTgsXG4gICAgICAgIDg4LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNTgsXG4gICAgICAgIDg4LFxuICAgICAgICAxNjksXG4gICAgICAgIDUzLFxuICAgICAgICAyMzYsXG4gICAgICAgIDc1LFxuICAgICAgICAxNDAsXG4gICAgICAgIDUsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjM1LFxuICAgICAgICAxOTYsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTgwLFxuICAgICAgICA1NixcbiAgICAgICAgODIsXG4gICAgICAgIDIzLFxuICAgICAgICAzNCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMTAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjU0LFxuICAgICAgICA1NCxcbiAgICAgICAgMjE0LFxuICAgICAgICA1NixcbiAgICAgICAgMjAyLFxuICAgICAgICAxMTAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTA0LFxuICAgICAgICAyMTIsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNTksXG4gICAgICAgIDY0LFxuICAgICAgICAyMTksXG4gICAgICAgIDkzLFxuICAgICAgICA5OSxcbiAgICAgICAgMTk2LFxuICAgICAgICAxNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIrYURDOGtZbk1PY2w1bzR6UU1hVEZBWGFuVXllS0JmTGN1bFNJbDlGL3NBPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJSbk9qMGpjSFFlcXJxYm05eDVJOE5nXCIsXG4gIFwicGhvbmVJZFwiOiBcImMyNjBkMzJjLWVmOWUtNDIwOC1hODA5LTJkMjAyZDVkODUwMlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4NCxcbiAgICAgIDk1LFxuICAgICAgMTEsXG4gICAgICAyNixcbiAgICAgIDE5NyxcbiAgICAgIDE3NCxcbiAgICAgIDIxNSxcbiAgICAgIDExNyxcbiAgICAgIDIxOSxcbiAgICAgIDYyLFxuICAgICAgMTcsXG4gICAgICAxMTIsXG4gICAgICA0LFxuICAgICAgMTMwLFxuICAgICAgMTEsXG4gICAgICAxMyxcbiAgICAgIDE3NSxcbiAgICAgIDE4LFxuICAgICAgMjI1LFxuICAgICAgMTUxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEwNixcbiAgICAgIDIxNyxcbiAgICAgIDI1LFxuICAgICAgMSxcbiAgICAgIDg0LFxuICAgICAgMjksXG4gICAgICAxNTQsXG4gICAgICAxNjksXG4gICAgICA4OSxcbiAgICAgIDIwOCxcbiAgICAgIDcyLFxuICAgICAgMjUyLFxuICAgICAgNTMsXG4gICAgICAyMDEsXG4gICAgICAxMDUsXG4gICAgICAzMixcbiAgICAgIDY1LFxuICAgICAgMTQzLFxuICAgICAgMjIzLFxuICAgICAgMTM2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIjhOU1lXR1kyXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ5MDM1NDcxNDI3OjU3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiTW92ZXR2cGx1c1wiLFxuICAgIFwibGlkXCI6IFwiNDQ2ODkzMDI1NDAzNjY6NTdAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTXlTanZFUEVPLzNrN2tHR0FNZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJhanBlTFljMkVyTkwydkdlcjlqZCthZ0YxNkNTdWFraUVQNnFwVzF4aEVFPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInhLd1NNY05wdDZ0aC9jcllGZ0s2R0V5T2hvTUNmSzZyREhSOE55NStueTNUdzVQTWJFdnlmSHFKUERMVjAzMERza3VtMXRCSnQydXVJTHJoQ3BlaENnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImlscDhKT295c3ZIaDdzTnVtRXVLY3BoOFpDbjBNaWVBb3lIV2VxMWpsTFFiVkdWdUNxdE1TQmZma0VuK21CU3RDQXRLcVhvQ1gxeGEvbm1BbHJGZENBPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwMzU0NzE0Mjc6NTdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA2NVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iaVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzMwNDc3MDQzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQjhJXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFCOEkuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJVWEZkMVVJSU9BWWU5QTdkMG5zRjdwSU1KTUhGYTNIVVdpVHVyRVpodGJnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjQyNjM3NDE3NzIsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyODMyMzM4ODQzNVwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
